// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcopavlcfnbwjqstseau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjb3BhdmxjZm5id2pxc3RzZWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTU3MjYsImV4cCI6MjA2NjU5MTcyNn0.mBnWyROVmLLE3d4MGRxjKajrtQGEa7O9NuTCusV6vcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);